In [2]:
!pip install keras

In [3]:
"""
    A simple neural network written in Keras (TensorFlow backend) to classify the IRIS data
"""

import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

iris_data = load_iris() # load the iris dataset

print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])

x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
#print(y)

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]
Neural Network Model Summary: 
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
fc2 (Dense)                  (None, 10)                110       
_________________________________________________________________
output (Dense)               (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/200
24/24 - 2s - loss: 1.3348 - accuracy: 0.3500
Epoch 2/200
24/24 - 0s - loss: 1.1955 - accuracy: 0.4667
Epoch 3/200
24/24 - 0s - loss: 1.1071 - accuracy: 0.3917
Epoch 4/200
24/24 - 0s - loss: 1.0273 - a

Epoch 127/200
24/24 - 0s - loss: 0.0612 - accuracy: 0.9833
Epoch 128/200
24/24 - 0s - loss: 0.0615 - accuracy: 0.9833
Epoch 129/200
24/24 - 0s - loss: 0.0607 - accuracy: 0.9917
Epoch 130/200
24/24 - 0s - loss: 0.0652 - accuracy: 0.9750
Epoch 131/200
24/24 - 0s - loss: 0.0676 - accuracy: 0.9667
Epoch 132/200
24/24 - 0s - loss: 0.0592 - accuracy: 0.9750
Epoch 133/200
24/24 - 0s - loss: 0.0609 - accuracy: 0.9833
Epoch 134/200
24/24 - 0s - loss: 0.0617 - accuracy: 0.9833
Epoch 135/200
24/24 - 0s - loss: 0.0606 - accuracy: 0.9833
Epoch 136/200
24/24 - 0s - loss: 0.0604 - accuracy: 0.9667
Epoch 137/200
24/24 - 0s - loss: 0.0599 - accuracy: 0.9750
Epoch 138/200
24/24 - 0s - loss: 0.0580 - accuracy: 0.9917
Epoch 139/200
24/24 - 0s - loss: 0.0592 - accuracy: 0.9833
Epoch 140/200
24/24 - 0s - loss: 0.0569 - accuracy: 0.9833
Epoch 141/200
24/24 - 0s - loss: 0.0629 - accuracy: 0.9833
Epoch 142/200
24/24 - 0s - loss: 0.0608 - accuracy: 0.9833
Epoch 143/200
24/24 - 0s - loss: 0.0555 - accuracy: 0.99

In [5]:
### Test sur le malware data

In [3]:
import pandas as pd
datamalw = pd.read_csv('data-train-model2021.csv')
datamalw.shape


(411, 46)

In [7]:
datamalw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 411 entries, 0 to 410
Data columns (total 46 columns):
 #   Column                                                     Non-Null Count  Dtype  
---  ------                                                     --------------  -----  
 0   items                                                      411 non-null    int64  
 1   CAMERA                                                     411 non-null    int64  
 2   GET_ACCOUNTS                                               411 non-null    int64  
 3   READ_CALENDAR                                              411 non-null    int64  
 4   READ_CALL_LOG                                              411 non-null    int64  
 5   READ_CONTACTS                                              411 non-null    int64  
 6   READ_EXTERNAL_STORAGE                                      410 non-null    float64
 7   READ_PHONE_STATE                                           410 non-null    float64
 8   READ_SMS  

In [8]:
datamalw.describe()


items      CAMERA  GET_ACCOUNTS  READ_CALENDAR  READ_CALL_LOG  \
count  411.00000  411.000000    411.000000     411.000000     411.000000   
mean   206.00000    0.216545      0.107056       0.038929       0.021898   
std    118.78973    0.412392      0.309561       0.193663       0.146528   
min      1.00000    0.000000      0.000000       0.000000       0.000000   
25%    103.50000    0.000000      0.000000       0.000000       0.000000   
50%    206.00000    0.000000      0.000000       0.000000       0.000000   
75%    308.50000    0.000000      0.000000       0.000000       0.000000   
max    411.00000    1.000000      1.000000       1.000000       1.000000   

       READ_CONTACTS  READ_EXTERNAL_STORAGE  READ_PHONE_STATE    READ_SMS  \
count     411.000000             410.000000        410.000000  411.000000   
mean        0.065693               0.321951          0.229268    0.017032   
std         0.248047               0.467795          0.420876    0.129547   
min         0.000000               0.000000          0.000000    0.000000   
25%         0.000000               0.000000          0.000000    0.000000   
50%         0.000000               0.000000          0.000000    0.000000   
75%         0.000000               1.000000          0.000000    0.000000   
max         1.000000               1.000000          1.000000    1.000000   

       RECEIVE_SMS  ...  READ_EXTERNAL_STORAGE\nREAD_PHONE_STATE\nREAD_SMS  \
count   411.000000  ...                                              411.0   
mean      0.026764  ...                                                0.0   
std       0.161590  ...                                                0.0   
min       0.000000  ...                                                0.0   
25%       0.000000  ...                                                0.0   
50%       0.000000  ...                                                0.0   
75%       0.000000  ...                                                0.0   
max       1.000000  ...                                                0.0   

       READ_PHONE_STATE\nREAD_SMS\nRECEIVE_SMS  \
count                                    411.0   
mean                                       0.0   
std                                        0.0   
min                                        0.0   
25%                                        0.0   
50%                                        0.0   
75%                                        0.0   
max                                        0.0   

       READ_SMS\nRECEIVE_SMS\nSEND_SMS  RECEIVE_SMS\nSEND_SMS\nWRITE_CALENDAR  \
count                            411.0                                  411.0   
mean                               0.0                                    0.0   
std                                0.0                                    0.0   
min                                0.0                                    0.0   
25%                                0.0                                    0.0   
50%                                0.0                                    0.0   
75%                                0.0                                    0.0   
max                                0.0                                    0.0   

       SEND_SMS\nWRITE_CALENDAR\nWRITE_CALL_LOG  \
count                                     411.0   
mean                                        0.0   
std                                         0.0   
min                                         0.0   
25%                                         0.0   
50%                                         0.0   
75%                                         0.0   
max                                         0.0   

       WRITE_CALENDAR\nWRITE_CALL_LOG\nACCESS_MOCK_LOCATION  \
count                                              411.0      
mean                                                 0.0      
std                                                  0.0      
min                                 

In [9]:

import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam


In [10]:
print(datamalw.Classe)

0      1
1      1
2      1
3      1
4      1
      ..
406    0
407    0
408    0
409    0
410    0
Name: Classe, Length: 411, dtype: int64


In [11]:
print('Example data: ')
print(datamalw.Classe)


Example data: 
0      1
1      1
2      1
3      1
4      1
      ..
406    0
407    0
408    0
409    0
410    0
Name: Classe, Length: 411, dtype: int64


In [12]:
x = datamalw
y_ = datamalw.Classe # Convert data to a single column

In [13]:
print(iris_data.target[:5])

NameError: name 'iris_data' is not defined

In [14]:
encoder = OneHotEncoder(sparse=False)
y = y_
#y = encoder.fit_transform(y_)

In [15]:
# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

In [16]:
model = Sequential()

In [17]:
model.add(Dense(2, input_shape=(46,46), activation='relu', name='fc1'))
model.add(Dense(2, activation='relu', name='fc2'))
model.add(Dense(1, activation='softmax', name='output'))


In [18]:
# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])


In [19]:
print('Neural Network Model Summary: ')
print(model.summary())


Neural Network Model Summary: 
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 46, 2)             94        
_________________________________________________________________
fc2 (Dense)                  (None, 46, 2)             6         
_________________________________________________________________
output (Dense)               (None, 46, 1)             3         
Total params: 103
Trainable params: 103
Non-trainable params: 0
_________________________________________________________________
None


In [20]:
# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=400)

Epoch 1/400
66/66 - 2s - loss: nan - accuracy: 0.5274
Epoch 2/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 3/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 4/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 5/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 6/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 7/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 8/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 9/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 10/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 11/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 12/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 13/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 14/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 15/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 16/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 17/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 18/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 19/400
66/66 

Epoch 139/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 140/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 141/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 142/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 143/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 144/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 145/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 146/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 147/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 148/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 149/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 150/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 151/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 152/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 153/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 154/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 155/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 156/400
66/66 - 0s - loss: nan - accuracy:

Epoch 286/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 287/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 288/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 289/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 290/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 291/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 292/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 293/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 294/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 295/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 296/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 297/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 298/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 299/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 300/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 301/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 302/400
66/66 - 0s - loss: nan - accuracy: 0.4878
Epoch 303/400
66/66 - 0s - loss: nan - accuracy:

In [21]:
# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=2, epochs=400)


Epoch 1/400
164/164 - 1s - loss: nan - accuracy: 0.4878
Epoch 2/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 3/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 4/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 5/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 6/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 7/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 8/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 9/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 10/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 11/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 12/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 13/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 14/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 15/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 16/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 17/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 18/400
164/164 - 0s - loss: nan - 

164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 140/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 141/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 142/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 143/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 144/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 145/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 146/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 147/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 148/400
164/164 - 1s - loss: nan - accuracy: 0.4878
Epoch 149/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 150/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 151/400
164/164 - 1s - loss: nan - accuracy: 0.4878
Epoch 152/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 153/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 154/400
164/164 - 1s - loss: nan - accuracy: 0.4878
Epoch 155/400
164/164 - 1s - loss: nan - accuracy: 0.4878
Epoch 156/400
164/164 - 0s -

Epoch 281/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 282/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 283/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 284/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 285/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 286/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 287/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 288/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 289/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 290/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 291/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 292/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 293/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 294/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 295/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 296/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 297/400
164/164 - 0s - loss: nan - accuracy: 0.4878
Epoch 298/400


In [22]:
results = model.evaluate(test_x, test_y)

3/3 [==============================] - 0s 5ms/step - loss: nan - accuracy: 0.4819


In [357]:
print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Final test set loss:  nan
Final test set accuracy: 0.421687


In [ ]:
"""
    A simple neural network written in Keras (TensorFlow backend) to classify the IRIS data
"""

import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

iris_data = load_iris() # load the iris dataset

print('Example data: ')
print(data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])

x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
#print(y)

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

In [379]:
# LSTM model

In [1]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense, LSTM
from keras.optimizers import Adam


In [4]:
x = datamalw
y_ = datamalw.Classe # Convert data to a single column

In [5]:
encoder = OneHotEncoder(sparse=False)
y = y_
#y = encoder.fit_transform(y_)

In [24]:
# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

In [25]:
model = Sequential()

In [29]:
#model.add(Dense(46, input_shape=(46,46), activation='relu', name='fc0'))
model.add(LSTM( input_shape=(1,1,), activation='relu', name='fc1'))
model.add(Dense(1, activation='relu', name='fc2'))
#model.add(Dense(1, activation='relu', name='fc3'))
model.add(Dense(1, activation='softmax', name='output'))
#model.add(LSTM((46), batch_input_shape=(1,5,1), return_sequences=False))


TypeError: __init__() missing 1 required positional argument: 'units'

In [16]:
# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])


In [17]:
print('Neural Network Model Summary: ')
print(model.summary())


Neural Network Model Summary: 
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (LSTM)                   (None, 1)                 12        
_________________________________________________________________
fc2 (Dense)                  (None, 1)                 2         
_________________________________________________________________
output (Dense)               (None, 1)                 2         
Total params: 16
Trainable params: 16
Non-trainable params: 0
_________________________________________________________________
None


In [18]:
# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

Epoch 1/200


ValueError: in user code:

    /home/varmant-charles/anaconda3/envs/conda_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    /home/varmant-charles/anaconda3/envs/conda_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /home/varmant-charles/anaconda3/envs/conda_env/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/varmant-charles/anaconda3/envs/conda_env/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/varmant-charles/anaconda3/envs/conda_env/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/varmant-charles/anaconda3/envs/conda_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
        outputs = model.train_step(data)
    /home/varmant-charles/anaconda3/envs/conda_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:754 train_step
        y_pred = self(x, training=True)
    /home/varmant-charles/anaconda3/envs/conda_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:998 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /home/varmant-charles/anaconda3/envs/conda_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/input_spec.py:219 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_1 is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 46)


In [684]:
#other test